services:
  privategpt:
    image: thespiritman/privategpt:ollama
    container_name: privategpt
    environment:
      OLLAMA_BASE_URL: "http://ollama:11434"
      USE_OLLAMA_DOCKER: true
    ports:
      - 8080:8001/tcp
    networks:
      - gpt

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ../ollama-models/:/root/.ollama/models
    networks:
      - gpt

networks:
  gpt:
